data_loader:
  google_colab: true
  input_path: '/content/drive/MyDrive/dataset'
  output_path: '/content/drive/MyDrive/results'
  file_pattern: 'data_*.parquet'
  date_format: '%Y-%m-%d'
  max_workers: 4
  chunk_size: 10000

reporting:
  default_format: 'html'
  save_plots: true
  save_tables: true
  max_table_rows: 500

execution:
  parallel: true
  max_detectors_parallel: 2
  timeout_minutes: 60

detectors:
  common:
    log_level: 'DEBUG'
    sample_fraction: 0.5

  isolation_forest:
    enabled: true
    contamination: 0.05
    n_estimators: 100
    features: ['requests', 'unique_ips']
  
  node_id_check:
    enabled: true
    required_columns:
      - node_id
      - main_rubric_id
      - content_is_longread

  activity_spikes:
    enabled: true
    time_resolution: '1H'  
    window_size: 5
    top_n: 10
    schedule_file: "/content/drive/MyDrive/aggrs_tv_program_epg_plan.csv"
    time_column: 'ts'

  page_view:
    enabled: true
    user_id_column: 'randPAS_user_agent_id'
    session_id_column: 'randPAS_session_id'

  untagged_bots:
    enabled: true
    top_n: 20

  night_activity:
    enabled: true
    time_column: 'ts'
    night_hours: [0, 1, 2, 3, 4, 5]

  users_devices:
    enabled: true
    required_columns:
      - ts
      - ua_is_tablet
      - ua_is_mobile
      - ua_is_pc
      - randPAS_session_id

plot_style: 'ggplot'
figure_size: [12, 6]
font_size: 12
title_size: 14
