data_loader:
  google_colab: true
  input_path: '/content/drive/MyDrive/dataset'
  output_path: '/content/drive/MyDrive/results'
  file_pattern: 'data_*.parquet'
  date_format: '%Y-%m-%d'
  max_workers: 4
  chunk_size: 10000

reporting:
  default_format: 'html'
  save_plots: true
  save_tables: true
  max_table_rows: 500

execution:
  parallel: true
  max_detectors_parallel: 2
  timeout_minutes: 60

detectors:
  common:
    log_level: 'WARNING'
    sample_fraction: 0.5
  
  isolation_forest:
    enabled: true
    contamination: 0.05
    n_estimators: 100
    
  node_id_check:
    enabled: true
    required_columns:
      - url
      - node_id
      - title

  activity_spikes:
    enabled: true
    resolution: '5min'
    threshold: 3.0
    schedule_file: "/content/drive/MyDrive/aggrs_tv_program_epg_plan.csv"
