data_loader:
  google_colab: false
  input_path: './data'
  output_path: './output'
  file_pattern: '*.parquet'
  date_format: '%Y-%m-%d'
  max_workers: 2
  chunk_size: 5000
  timestamp_column: 'ts'

reporting:
  default_format: 'console'
  save_plots: false
  save_tables: true
  max_table_rows: 100

execution:
  parallel: false
  timeout_minutes: 30

detectors:
  common:
    log_level: 'DEBUG'
    sample_fraction: 0.1

  isolation_forest:
    enabled: true
    contamination: 0.1
    n_estimators: 50
    features: ['requests', 'unique_ips']

  node_id_check:
    enabled: true
    required_columns: ['url', 'node_id', 'content_type']
    validate_hourly: true
    time_column: 'ts'

  activity_spikes:
    enabled: true
    time_resolution: "1min"
    window_size: 5
    top_n: 50
    schedule_file: "data/aggrs_tv_program_epg_plan.csv"
    time_column: 'ts'

  page_view:
    enabled: true
    user_id_column: randPAS_user_agent_id
    session_id_column: randPAS_session_id

  untagged_bots:
    enabled: true
    top_n: 10

  night_activity:
    enabled: true
    min_requests_threshold: 100  # можно добавить параметров позже при необходимости

plot_style: "ggplot"
figure_size: [12, 6]
font_size: 12
title_size: 14
