
data_loader:
  google_colab: false
  input_path: './data'
  output_path: './output'
  file_pattern: 'sample_*.parquet'
  date_format: '%Y-%m-%d'
  max_workers: 2
  chunk_size: 5000

reporting:
  default_format: 'console'
  save_plots: false
  save_tables: true
  max_table_rows: 100

execution:
  parallel: false
  timeout_minutes: 30

detectors:
  common:
    log_level: 'DEBUG'
    sample_fraction: 0.1
  
  isolation_forest:
    enabled: true
    contamination: 0.1
    n_estimators: 50
    features: ['requests', 'unique_ips']
    
node_id_check:
    enabled: true
    required_columns: ['url', 'node_id', 'content_type']
    validate_hourly: true

activity_spikes:
    enabled: true
    time_resolution: "1min"  # Более точный анализ
    window_size: 5           # Более чувствительный детектор
    top_n: 50                # Больше аномалий
    schedule_file: "data/tv_schedule.csv"

plot_style: "ggplot"
figure_size: [12, 6]
font_size: 12
title_size: 14
