data_loader:
  google_colab: false              # Отключить Colab-специфичные функции
  datasets_path: './data'          # Локальный путь к данным
  default_file_mask: '*.parquet'
  date_format: '%Y-%m-%d'
  max_files: 50

reporting:
  output_dir: './output'
  default_format: 'console'        # Удобный вывод в консоль при разработке
  save_raw_data: true              # Сохранять сырые данные для отладки

detectors:
  common:
    log_level: 'DEBUG'            # Подробные логи при разработке
    sample_size: 5000
  
  node_id_check:
    required_columns:
      - url
      - node_id
    check_hourly_distribution: false  # Упрощенная проверка локально

  activity_spikes:
    time_resolution: '15min'       # Меньше детализация для скорости
    spike_threshold: 2.5
