data_loader:
  google_colab: false
  input_path: '/mnt/data/input'
  output_path: '/mnt/data/output'
  file_pattern: 'data_*.parquet'
  date_format: '%Y-%m-%d'
  max_workers: 8
  chunk_size: 100000

reporting:
  default_format: 'json'
  save_plots: true
  save_tables: true
  max_table_rows: 1000

execution:
  parallel: true
  max_detectors_parallel: 4
  timeout_minutes: 120

detectors:
  common:
    log_level: 'INFO'
    sample_fraction: 1.0
  
  isolation_forest:
    enabled: true
    contamination: 0.05
    n_estimators: 100
    features: ['requests', 'unique_ips', 'bot_ratio']
    
  node_id_check:
    enabled: true
    required_columns:
      - url
      - node_id
      - content_type
    validate_hourly: true

  activity_spikes:
    enabled: true
    resolution: '1min'
    threshold: 3.5
    min_duration: '5min'
